In [5]:
import networkx as nx
import numpy as np
import scipy.linalg as ln

G = nx.Graph()
G.add_edges_from([(1,2),(2,3),(3,4)])
a = nx.adjacency_matrix(G)
ad = a.todense()
ad

matrix([[0, 1, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [0, 0, 1, 0]], dtype=int64)

In [9]:
ad*ad*ad

matrix([[0, 2, 0, 1],
        [2, 0, 3, 0],
        [0, 3, 0, 2],
        [1, 0, 2, 0]], dtype=int64)

In [6]:
import networkx as nx
from numpy import linalg as LA

G = nx.Graph([(1,2),(1,4),(2,4),(2,3),(3,4),(3,5),(4,5)])
a = (nx.adjacency_matrix(G)).todense()
w, v = LA.eigh(a)
print(w)
print(v)

[-1.61803399 -1.47283391 -0.46259842  0.61803399  2.93543233]
[[ -3.71748034e-01   4.29374351e-01   4.39042241e-01  -6.01500955e-01
    3.50541834e-01]
 [  6.01500955e-01   1.37844975e-01  -5.10036310e-01  -3.71748034e-01
    4.69959281e-01]
 [ -6.01500955e-01   1.37844975e-01  -5.10036310e-01   3.71748034e-01
    4.69959281e-01]
 [ -7.21644966e-16  -7.70242078e-01   3.06936062e-01  -5.55111512e-17
    5.59032552e-01]
 [  3.71748034e-01   4.29374351e-01   4.39042241e-01   6.01500955e-01
    3.50541834e-01]]


In [23]:
import networkx as nx

G = nx.Graph([(1,2),(1,4),(2,4),(2,3),(3,4),(3,5),(4,5),(1,3),(1,5),(2,5)])
c = nx.communicability(G)
c

{1: {1: 11.21393355956598,
  2: 10.846054118394525,
  3: 10.846054118394532,
  4: 10.846054118394532,
  5: 10.846054118394534},
 2: {1: 10.846054118394525,
  2: 11.213933559565954,
  3: 10.846054118394518,
  4: 10.846054118394518,
  5: 10.84605411839452},
 3: {1: 10.846054118394532,
  2: 10.846054118394518,
  3: 11.213933559565966,
  4: 10.846054118394525,
  5: 10.846054118394527},
 4: {1: 10.846054118394532,
  2: 10.846054118394518,
  3: 10.846054118394525,
  4: 11.213933559565966,
  5: 10.846054118394527},
 5: {1: 10.846054118394534,
  2: 10.84605411839452,
  3: 10.846054118394527,
  4: 10.846054118394527,
  5: 11.213933559565968}}

In [1]:
import networkx as nx

G = nx.Graph([(1,2),(1,4),(2,4),(2,3),(3,4),(3,5),(4,5)])
c = nx.communicability(G)
c

{1: {1: 3.1760656034507697,
  2: 3.345091689078022,
  3: 2.604063767554446,
  4: 3.6989609699785944,
  5: 1.7787690869507244},
 2: {1: 3.345091689078022,
  2: 4.655032127678272,
  3: 3.9987635327018074,
  4: 4.824058213305527,
  5: 2.6040637675544454},
 3: {1: 2.604063767554446,
  2: 3.9987635327018074,
  3: 4.655032127678278,
  4: 4.82405821330553,
  5: 3.345091689078026},
 4: {1: 3.6989609699785944,
  2: 4.824058213305527,
  3: 4.82405821330553,
  4: 6.079931933728424,
  5: 3.6989609699785952},
 5: {1: 1.7787690869507244,
  2: 2.6040637675544454,
  3: 3.345091689078026,
  4: 3.6989609699785952,
  5: 3.1760656034507706}}

In [ ]:
c