In [4]:
import numpy as np
from scipy import linalg as LA
x = np.matrix( ((1,-1,0,0,0), (-1,3,-1,0,-1),(0,-1,2,-1,0),(0,0,-1,2,-1),(0,-1,0,-1,2)))
e_vals, e_vecs = LA.eig(x)
e_vals

array([ -2.22044605e-16+0.j,   8.29913513e-01+0.j,   4.48119430e+00+0.j,
         2.68889218e+00+0.j,   2.00000000e+00+0.j])

In [5]:
y = np.matrix( ((2,0,-1,0,-1), (0,1,0,-1,0),(-1,0,2,0,-1),(0,-1,0,1,0),(-1,0,-1,0,2)))
e_vals, e_vecs = LA.eig(y)
e_vals

array([  3.00000000e+00+0.j,  -2.22044605e-16+0.j,   0.00000000e+00+0.j,
         2.00000000e+00+0.j,   3.00000000e+00+0.j])

In [6]:
z = np.matrix( ((1,0,0,-1,0), (0,0,0,0,0),(0,0,0,0,0),(-1,0,0,1,0),(0,0,0,0,0)))
e_vals, e_vecs = LA.eig(z)
e_vals

array([ 2.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j])

In [7]:
a = np.matrix( ((4,-1,-1,-1,-1), (-1,4,-1,-1,-1),(-1,-1,4,-1,-1),(-1,-1,-1,4,-1),(-1,-1,-1,-1,4)))
e_vals, e_vecs = LA.eig(a)
e_vals

array([ 5.+0.j,  0.+0.j,  5.+0.j,  5.+0.j,  5.+0.j])

In [8]:
a = np.matrix( ((3,-1,-1,-1), (-1,3,-1,-1),(-1,-1,3,-1),(-1,-1,-1,3)))
e_vals, e_vecs = LA.eig(a)
e_vals

array([  4.00000000e+00+0.j,  -1.11022302e-16+0.j,   4.00000000e+00+0.j,
         4.00000000e+00+0.j])

In [15]:
import networkx as nx
import numpy as np

G = nx.Graph()
edge_list = [(1,2),(2,3),(2,5),(3,4),(4,5)]
G.add_edges_from(edge_list)

def pathlaplacian(G,k):
    nodelist = nx.nodes(G)
    nsize = len(nodelist)
    mp = np.zeros(shape=(nsize,nsize))
    i = 1
    for n in nodelist:
        c = 0
        for m in nodelist[i:]:
            s = nx.shortest_path_length(G, source=n,target=m)
            if(s==k):
                mp[n-1,m-1]= mp[m-1,n-1]= -1
        i = i+1
        mp[n-1,n-1]= np.sum(mp[n-1]*-1)
    return mp

In [19]:
G = nx.Graph()
edge_list = [(1,2),(2,3),(2,5),(3,4),(4,5)]
G.add_edges_from(edge_list)

pathlaplacian(G,3)

array([[ 1.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
m = 