In [1]:
import networkx as nx
import numpy as np

def kpathlaplacian(G, k):
    if k==1:
        L = nx.laplacian_matrix(G).toarray()
    else:
        nodelist= G.nodes()
        nsize = len(nodelist)
        L = np.zeros(shape=(nsize,nsize))
        i=1
        for n in nodelist:
            for m in nodelist[i:]:
                if((nx.shortest_path_length(G, source=n, target=m))==k):
                    L[n-1,m-1]= L[m-1,n-1]= -1
            i = i+1
            L[n-1,n-1] = np.sum(L[n-1]*-1)
    return L         

In [14]:
import networkx as nx 

G = nx.Graph()
e_list = [(1,2),(2,3),(1,3),(3,4),(2,4),(3,5),(4,5),(5,6),(3,6),
          (6,7),(6,8),(7,8),(7,9),(8,9),(8,10),(9,10),(9,11),(10,11),
          (10,12),(11,12),(10,16),(12,13),(12,16),(13,14),(14,16),
          (13,16),(14,15),(15,16)]
G.add_edges_from(e_list)
#nx.degree(G)
n_lst=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
D = nx.floyd_warshall_numpy(G, nodelist=n_lst, weight='weight')
D

matrix([[ 0.,  1.,  1.,  2.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,
          6.,  6.,  5.],
        [ 1.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,
          6.,  6.,  5.],
        [ 1.,  1.,  0.,  1.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,
          5.,  5.,  4.],
        [ 2.,  1.,  1.,  0.,  1.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,
          6.,  6.,  5.],
        [ 2.,  2.,  1.,  1.,  0.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,
          5.,  5.,  4.],
        [ 2.,  2.,  1.,  2.,  1.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,
          4.,  4.,  3.],
        [ 3.,  3.,  2.,  3.,  2.,  1.,  0.,  1.,  1.,  2.,  2.,  3.,  4.,
          4.,  4.,  3.],
        [ 3.,  3.,  2.,  3.,  2.,  1.,  1.,  0.,  1.,  1.,  2.,  2.,  3.,
          3.,  3.,  2.],
        [ 4.,  4.,  3.,  4.,  3.,  2.,  1.,  1.,  0.,  1.,  1.,  2.,  3.,
          3.,  3.,  2.],
        [ 4.,  4.,  3.,  4.,  3.,  2.,  2.,  1.,  1.,  0.,  1.,  1.,  2.,
          2.,  2.,  1.],
        [ 

In [12]:
from scipy import linalg as LA
e_vals, e_vecs = LA.eig(D)
e_vals

array([  7.17872162e+00+0.j,   6.87170815e+00+0.j,   1.59126727e-15+0.j,
         5.72396929e+00+0.j,   5.34004199e+00+0.j,   4.82354784e+00+0.j,
         7.08067545e-01+0.j,   4.17163420e+00+0.j,   3.86001245e+00+0.j,
         3.41231577e+00+0.j,   3.08388928e+00+0.j,   2.61426103e+00+0.j,
         1.12429306e+00+0.j,   1.78845256e+00+0.j,   1.68343114e+00+0.j,
         1.61565406e+00+0.j])

In [15]:
rows = D.shape[0]
cols = D.shape[1]

for x in range(0, rows):
    for y in range(0, cols):
        if (D[x,y]==2):
            D[x,y]=-(1)
        else:
            D[x,y]=0
    D[x,x]= np.sum(D[x]*-1)
D

matrix([[ 3.,  0.,  0., -1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [ 0.,  2.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [ 0.,  0.,  2.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [-1.,  0.,  0.,  2.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  4.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [-1., -1.,  0., -1.,  0.,  5.,  0.,  0., -1., -1.,  0.,  0.,  0.,
          0.,  0.,  0.],
        [ 0.,  0., -1.,  0., -1.,  0.,  4.,  0.,  0., -1., -1.,  0.,  0.,
          0.,  0.,  0.],
        [ 0.,  0., -1.,  0., -1.,  0.,  0.,  5.,  0.,  0., -1., -1.,  0.,
          0.,  0., -1.],
        [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  3.,  0.,  0., -1.,  0.,
          0.,  0., -1.],
        [ 0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  5.,  0.,  0., -1.,
         -1., -1.,  0.],
        [ 

In [16]:
e_vals, e_vecs = LA.eig(D)
e_vals

array([  7.17872162e+00+0.j,   6.87170815e+00+0.j,   1.59126727e-15+0.j,
         5.72396929e+00+0.j,   5.34004199e+00+0.j,   4.82354784e+00+0.j,
         7.08067545e-01+0.j,   4.17163420e+00+0.j,   3.86001245e+00+0.j,
         3.41231577e+00+0.j,   3.08388928e+00+0.j,   2.61426103e+00+0.j,
         1.12429306e+00+0.j,   1.78845256e+00+0.j,   1.68343114e+00+0.j,
         1.61565406e+00+0.j])

In [10]:
from scipy import linalg as LA

L_3 = kpathlaplacian(G, k=3)
e_vals, e_vecs = LA.eig(L_3)
e_vals

array([  7.62322655e+00 +0.00000000e+00j,
         6.36056642e+00 +0.00000000e+00j,
         5.75345078e+00 +0.00000000e+00j,
         4.50037010e+00 +0.00000000e+00j,
         2.13289844e-16 +0.00000000e+00j,
         3.16433895e-01 +0.00000000e+00j,
         9.31326762e-01 +0.00000000e+00j,
         1.13191393e+00 +0.00000000e+00j,
         3.49832124e+00 +0.00000000e+00j,
         1.86840518e+00 +0.00000000e+00j,
         3.01598514e+00 +0.00000000e+00j,
         2.00000000e+00 +0.00000000e+00j,
         3.00000000e+00 +0.00000000e+00j,
         2.00000000e+00 +2.79223177e-16j,
         2.00000000e+00 -2.79223177e-16j,   2.00000000e+00 +0.00000000e+00j])

In [18]:
G = nx.Graph()
e_list = [(1,2),(2,3),(1,3),(3,4),(2,4),(3,5),(4,5),(5,6),(3,6),
          (6,7),(6,8),(7,8),(7,9),(8,9),(8,10),(9,10),(9,11),(10,11),
          (10,12),(11,12),(10,16),(12,13),(12,16),(13,14),(14,16),
          (13,16),(14,15),(15,16),(1,17),(17,15),(17,18),(1,18),(18,15)]
G.add_edges_from(e_list)
nx.degree(G)

{1: 4,
 2: 3,
 3: 5,
 4: 3,
 5: 3,
 6: 4,
 7: 3,
 8: 4,
 9: 4,
 10: 5,
 11: 3,
 12: 4,
 13: 3,
 14: 3,
 15: 4,
 16: 5,
 17: 3,
 18: 3}

In [12]:
L_2 = kpathlaplacian(G, k=2)
e_vals, e_vecs = LA.eig(L_2)
e_vals

array([ -2.66453526e-15+0.j,   7.50978545e+00+0.j,   7.31055365e+00+0.j,
         7.08316794e+00+0.j,   6.31125258e+00+0.j,   1.06601913e+00+0.j,
         5.37029030e+00+0.j,   1.53502992e+00+0.j,   1.96792107e+00+0.j,
         5.08313035e+00+0.j,   4.80551461e+00+0.j,   4.35647754e+00+0.j,
         3.87743634e+00+0.j,   3.47820668e+00+0.j,   2.77110712e+00+0.j,
         3.08764595e+00+0.j,   2.38646136e+00+0.j,   4.00000000e+00+0.j])