In [5]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

G = nx.grid_graph([4,4], periodic=False)
#nx.draw(G)
#plt.show()

In [7]:
#n_lst=[(0,1),(1,3),(3,0),(0,3),(2,3),(3,3),(0,2),(1,2),(2,2),(3,2),
        #(1,1),(2,1),(3,1),(0,0),(1,0),(2,0)]
n_lst = [(0,3),(0,2),(0,1),(0,0),(1,3),(1,2),(1,1),(1,0),(2,3),(2,2),
      (2,1),(2,0),(3,3),(3,2),(3,1),(3,0)]
D =  nx.floyd_warshall_numpy(G, nodelist=n_lst, weight='weight')


In [8]:
rows = D.shape[0]
cols = D.shape[1]

for x in range(0, rows):
    for y in range(0, cols):
        if (D[x,y]==1):
            D[x,y]=-(1)
        elif (D[x,y]==2):
            D[x,y]=-(1/4)
        elif (D[x,y]==3):
            D[x,y]=-(1/9)
        elif (D[x,y]==4):
            D[x,y]=-(1/16)
        elif (D[x,y]==5):
            D[x,y]=-(1/25)
        elif (D[x,y]==6):
            D[x,y]=-(1/36)
    D[x,x]= np.sum(D[x]*-1)
D

matrix([[ 3.48972222, -1.        , -0.25      , -0.11111111, -1.        ,
         -0.25      , -0.11111111, -0.0625    , -0.25      , -0.11111111,
         -0.0625    , -0.04      , -0.11111111, -0.0625    , -0.04      ,
         -0.02777778],
        [-1.        ,  4.67194444, -1.        , -0.25      , -0.25      ,
         -1.        , -0.25      , -0.11111111, -0.11111111, -0.25      ,
         -0.11111111, -0.0625    , -0.0625    , -0.11111111, -0.0625    ,
         -0.04      ],
        [-0.25      , -1.        ,  4.67194444, -1.        , -0.11111111,
         -0.25      , -1.        , -0.25      , -0.0625    , -0.11111111,
         -0.25      , -0.11111111, -0.04      , -0.0625    , -0.11111111,
         -0.0625    ],
        [-0.11111111, -0.25      , -1.        ,  3.48972222, -0.0625    ,
         -0.11111111, -0.25      , -1.        , -0.04      , -0.0625    ,
         -0.11111111, -0.25      , -0.02777778, -0.04      , -0.0625    ,
         -0.11111111],
        [-1.        

In [9]:
import numpy as np
import pandas as pd

df = pd.DataFrame(data=D.astype(float))
df.to_csv('laplacian1.csv', sep=',', header=False, float_format='%.4f', index=False)


In [23]:
D

matrix([[ 4.67194444, -0.11111111, -0.0625    , -0.25      , -0.0625    ,
         -0.04      , -1.        , -0.25      , -0.11111111, -0.0625    ,
         -1.        , -0.25      , -0.11111111, -1.        , -0.25      ,
         -0.11111111],
        [-0.11111111,  4.67194444, -0.04      , -1.        , -1.        ,
         -0.25      , -0.25      , -1.        , -0.25      , -0.11111111,
         -0.25      , -0.11111111, -0.0625    , -0.0625    , -0.11111111,
         -0.0625    ],
        [-0.0625    , -0.04      ,  3.48972222, -0.02777778, -0.0625    ,
         -0.11111111, -0.04      , -0.0625    , -0.11111111, -0.25      ,
         -0.11111111, -0.25      , -1.        , -0.11111111, -0.25      ,
         -1.        ],
        [-0.25      , -1.        , -0.02777778,  3.48972222, -0.25      ,
         -0.11111111, -1.        , -0.25      , -0.11111111, -0.0625    ,
         -0.11111111, -0.0625    , -0.04      , -0.11111111, -0.0625    ,
         -0.04      ],
        [-0.0625    

In [39]:
L_u = D[3:,3:]
L_u

matrix([[ 3.48972222, -0.25      , -0.11111111, -1.        , -0.25      ,
         -0.11111111, -0.0625    , -0.11111111, -0.0625    , -0.04      ,
         -0.11111111, -0.0625    , -0.04      ],
        [-0.25      ,  4.67194444, -1.        , -0.11111111, -0.25      ,
         -1.        , -0.25      , -0.11111111, -0.25      , -0.11111111,
         -0.04      , -0.0625    , -0.11111111],
        [-0.11111111, -1.        ,  3.48972222, -0.0625    , -0.11111111,
         -0.25      , -1.        , -0.0625    , -0.11111111, -0.25      ,
         -0.02777778, -0.04      , -0.0625    ],
        [-1.        , -0.11111111, -0.0625    ,  4.67194444, -1.        ,
         -0.25      , -0.11111111, -0.25      , -0.11111111, -0.0625    ,
         -0.25      , -0.11111111, -0.0625    ],
        [-0.25      , -0.25      , -0.11111111, -1.        ,  6.00694444,
         -1.        , -0.25      , -1.        , -0.25      , -0.11111111,
         -0.11111111, -0.25      , -0.11111111],
        [-0.111

In [38]:
L_u = D[3:,3:]
B_T = D[3:,:3]
M1 = np.matrix([[1], [0],[0]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

matrix([[ 0.3233404 ],
        [ 0.25386773],
        [ 0.27218854],
        [ 0.46748425],
        [ 0.33895493],
        [ 0.31510865],
        [ 0.29049825],
        [ 0.44537198],
        [ 0.34424346],
        [ 0.27103464],
        [ 0.54049922],
        [ 0.40470093],
        [ 0.30188053]])

In [3]:
L_u = L[3:,3:]
B_T = L[3:,:3]
-B_T

matrix([[0, 1, 0],
        [0, 1, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 1]], dtype=int64)

In [4]:
M1 = np.matrix([[1], [0],[0]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

matrix([[ 0.26541755],
        [ 0.13261927],
        [ 0.15994868],
        [ 0.5308351 ],
        [ 0.32708775],
        [ 0.23790912],
        [ 0.1872781 ],
        [ 0.53960677],
        [ 0.30465137],
        [ 0.16397649],
        [ 0.76334397],
        [ 0.52668795],
        [ 0.27711311]])

In [5]:
M2 = np.matrix([[0], [1],[0]])
R_hs = -B_T *M2
x_l2 = np.linalg.solve(L_u, R_hs)
x_l2

matrix([[ 0.70602978],
        [ 0.67112212],
        [ 0.54238148],
        [ 0.41205955],
        [ 0.53014888],
        [ 0.47098487],
        [ 0.41364084],
        [ 0.23755109],
        [ 0.26902766],
        [ 0.22755617],
        [ 0.07551392],
        [ 0.15102784],
        [ 0.1400185 ]])

In [6]:
M3 = np.matrix([[0], [0],[1]])
R_hs = -B_T *M3
x_l3 = np.linalg.solve(L_u, R_hs)
x_l3

matrix([[ 0.02855267],
        [ 0.19625862],
        [ 0.29766984],
        [ 0.05710535],
        [ 0.14276337],
        [ 0.29110601],
        [ 0.39908106],
        [ 0.22284214],
        [ 0.42632097],
        [ 0.60846734],
        [ 0.16114211],
        [ 0.32228421],
        [ 0.5828684 ]])

In [7]:
import numpy as np

M1 = np.matrix([[1], [0]])
L_u = np.matrix([[2,-1,0,0], [-1,3,-1,0],[0,-1,3,-1],[0,0,-1,2]]) 
B_T = np.matrix([[-1,0], [0,-1],[-1,0],[0,-1]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

matrix([[ 0.71428571],
        [ 0.42857143],
        [ 0.57142857],
        [ 0.28571429]])

In [8]:
M2 = np.matrix([[0], [1]])
L_u = np.matrix([[2,-1,0,0], [-1,3,-1,0],[0,-1,3,-1],[0,0,-1,2]]) 
B_T = np.matrix([[-1,0], [0,-1],[-1,0],[0,-1]])
R_hs = -B_T *M2
x_l2 = np.linalg.solve(L_u, R_hs)
x_l2

matrix([[ 0.28571429],
        [ 0.57142857],
        [ 0.42857143],
        [ 0.71428571]])

In [9]:
M1 = np.matrix([[1], [0]])

L_u2 = L_u + (0.25*(np.matrix([[2,0,-1,0], [0,2,0,-1],[-1,0,2,0],[0,-1,0,2]]))) 
B_t2 = B_T + (0.25*(np.matrix([[0,-1], [-1,0],[0,-1],[-1,0]])))
R_hs = -(B_t2) *M1
x_l1 = np.linalg.solve(L_u2, R_hs)
x_l1

matrix([[ 0.63157895],
        [ 0.43859649],
        [ 0.56140351],
        [ 0.36842105]])

In [10]:
M2 = np.matrix([[0], [1]])
L_u2 = L_u + (0.25*(np.matrix([[2,0,-1,0], [0,2,0,-1],[-1,0,2,0],[0,-1,0,2]]))) 
B_t2 = B_T + (0.25*(np.matrix([[0,-1], [-1,0],[0,-1],[-1,0]])))
R_hs = -(B_t2) *M2
x_l2 = np.linalg.solve(L_u2, R_hs)
x_l2

matrix([[ 0.36842105],
        [ 0.56140351],
        [ 0.43859649],
        [ 0.63157895]])

In [28]:
L_u
np.savetxt('laptest.txt',L_u, delimiter=',')

In [32]:
import numpy as np
import pandas as pd

mat = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data=mat.astype(float))
df.to_csv('outfile1.csv', sep=',', header=False, float_format='%.2f', index=False)


In [12]:
M2 = np.matrix([[0], [1]])
L_u = np.matrix([[2,0,-1,0], [0,2,0,-1],[-1,0,2,0],[0,-1,0,2]]) 
B_T = np.matrix([[0,-1], [-1,0],[0,-1],[-1,0]])
R_hs = -B_T *M2
x_l2 = np.linalg.solve(L_u, R_hs)
x_l2

matrix([[ 1.],
        [ 0.],
        [ 1.],
        [ 0.]])

In [11]:
G = nx.Graph()
e_lst = [(4,2),(4,7),(2,5),(2,8),(5,6),(5,9),(6,10),
         (7,8),(7,1),(8,9),(8,11),(9,10),(9,12),(10,13),
          (1,11),(1,14),(11,12),(11,15),(12,13),(12,16),(13,3),
          (14,15),(15,16),(16,3)]
G.add_edges_from(e_lst)
L = nx.laplacian_matrix(G, nodelist= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
L = L.todense()
L

matrix([[ 3,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0, -1,  0],
        [ 0,  3,  0, -1, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
        [ 0, -1,  0,  2,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  3, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  2,  0,  0,  0, -1,  0,  0,  0,  0,  0],
        [-1,  0,  0, -1,  0,  0,  3, -1,  0,  0,  0,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  0,  0, -1,  4, -1,  0, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0, -1,  4, -1,  0, -1,  0,  0,  0],
        [ 0,  0,  0,  0,  0, -1,  0,  0, -1,  3,  0,  0, -1,  0,  0],
        [-1,  0,  0,  0,  0,  0,  0, -1,  0,  0,  4, -1,  0,  0, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  3, -1,  0,  0],
        [ 0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0, -1,  3,  0,  0],
        [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -1],
        [ 0,  0,  0,

In [14]:
L_u = L[3:,3:]
B_T = L[3:,:3]
M1 = np.matrix([[1], [0],[0]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

matrix([[ 0.26541755],
        [ 0.13261927],
        [ 0.15994868],
        [ 0.5308351 ],
        [ 0.32708775],
        [ 0.23790912],
        [ 0.1872781 ],
        [ 0.53960677],
        [ 0.30465137],
        [ 0.16397649],
        [ 0.76334397],
        [ 0.52668795],
        [ 0.27711311]])

In [15]:
M2 = np.matrix([[0], [1],[0]])
R_hs = -B_T *M2
x_l2 = np.linalg.solve(L_u, R_hs)
x_l2

matrix([[ 0.70602978],
        [ 0.67112212],
        [ 0.54238148],
        [ 0.41205955],
        [ 0.53014888],
        [ 0.47098487],
        [ 0.41364084],
        [ 0.23755109],
        [ 0.26902766],
        [ 0.22755617],
        [ 0.07551392],
        [ 0.15102784],
        [ 0.1400185 ]])

In [16]:
M3 = np.matrix([[0], [0],[1]])
R_hs = -B_T *M3
x_l3 = np.linalg.solve(L_u, R_hs)
x_l3

matrix([[ 0.02855267],
        [ 0.19625862],
        [ 0.29766984],
        [ 0.05710535],
        [ 0.14276337],
        [ 0.29110601],
        [ 0.39908106],
        [ 0.22284214],
        [ 0.42632097],
        [ 0.60846734],
        [ 0.16114211],
        [ 0.32228421],
        [ 0.5828684 ]])

In [12]:
import networkx as nx
import numpy as np

def kpathlaplacian(G, k, nodelist=G.nodes()):
    if k==1:
        L = nx.laplacian_matrix(G, nodelist).toarray()
    else:
        nsize = len(nodelist)
        L = np.zeros(shape=(nsize,nsize))
        i=1
        for n in nodelist:
            for m in nodelist[i:]:
                if((nx.shortest_path_length(G, source=n, target=m))==k):
                    L[n-1,m-1]= L[m-1,n-1]= -1
            i = i+1
            L[n-1,n-1] = np.sum(L[n-1]*-1)
    return L                 

In [22]:
import numpy.linalg as lng

nlist = [9,2,16,1,3,4,5,6,7,8,10,11,12,13,14,15]
L_3 =kpathlaplacian(G, k=3, nodelist=nlist)
L_3

array([[ 4.,  0.,  0., -1.,  0.,  0., -1.,  0.,  0., -1.,  0.,  0., -1.,
         0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0., -1.,  0.,  0.,
        -1.,  0.,  0.],
       [ 0.,  0.,  4.,  0., -1.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0.,
         0., -1.,  0.],
       [-1.,  0.,  0.,  4.,  0., -1.,  0.,  0.,  0.,  0., -1.,  0.,  0.,
         0.,  0., -1.],
       [ 0.,  0., -1.,  0.,  4.,  0.,  0., -1.,  0.,  0., -1.,  0.,  0.,
        -1.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  4.,  0.,  0.,  0.,  0.,  0., -1., -1.,
         0., -1.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  4.,  0., -1.,  0.,  0.,  0.,  0.,
        -1.,  0., -1.],
       [ 0., -1.,  0.,  0., -1.,  0.,  0.,  4.,  0., -1.,  0.,  0.,  0.,
         0., -1.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0., -1.,  0.,  4.,  0.,  0., -1.,  0.,
         0., -1.,  0.],
       [-1.,  0., -1.,  0.,  0.,  0.,  0., -1.,  0.,  4.,  0.,  0.,  0.,
         0.,  0., -1.],
       [ 0., -1.,  0., -1., -1

In [19]:
L_u = L_3[3:,3:]
B_T = L_3[3:,:3]
M1 = np.matrix([[1], [0],[0]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

matrix([[ 0.55048094],
        [ 0.18612652],
        [ 0.37661107],
        [ 0.48646453],
        [ 0.20340318],
        [ 0.22298673],
        [ 0.42673594],
        [ 0.3217721 ],
        [ 0.20473215],
        [ 0.55048094],
        [ 0.2193308 ],
        [ 0.20075024],
        [ 0.50354059]])

In [20]:
L_u = L_2[3:,3:]
B_T = L_2[3:,:3]
M1 = np.matrix([[1], [0],[0]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

NameError: name 'L_2' is not defined

In [19]:
nlist = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
L_1 =kpathlaplacian(G, k=1, nodelist=nlist)
L_2 = (1/4)* (kpathlaplacian(G, k=2, nodelist=nlist))
L_3 = (1/9)*(kpathlaplacian(G, k=3, nodelist=nlist))
L_4 = (1/16)*(kpathlaplacian(G, k=4, nodelist=nlist))
L_5 = (1/25)*(kpathlaplacian(G, k=5, nodelist=nlist))
L_6 = (1/36)*(kpathlaplacian(G, k=6, nodelist=nlist))
L = L_1+L_2+L_3+L_4+L_5+L_6
#np.savetxt('laplacianpotential.txt',L, delimiter=',')
#L
dd = pd.DataFrame(data=L.astype(float))
dd.to_csv('lapla.csv', sep=',', header=False, float_format='%.4f', index=False)


In [17]:
L

array([[ 4.67194444, -0.11111111, -0.0625    , -0.25      , -0.0625    ,
        -0.04      , -1.        , -0.25      , -0.11111111, -0.0625    ,
        -1.        , -0.25      , -0.11111111, -1.        , -0.25      ,
        -0.11111111],
       [-0.11111111,  4.67194444, -0.04      , -1.        , -1.        ,
        -0.25      , -0.25      , -1.        , -0.25      , -0.11111111,
        -0.25      , -0.11111111, -0.0625    , -0.0625    , -0.11111111,
        -0.0625    ],
       [-0.0625    , -0.04      ,  3.48972222, -0.02777778, -0.0625    ,
        -0.11111111, -0.04      , -0.0625    , -0.11111111, -0.25      ,
        -0.11111111, -0.25      , -1.        , -0.11111111, -0.25      ,
        -1.        ],
       [-0.25      , -1.        , -0.02777778,  3.48972222, -0.25      ,
        -0.11111111, -1.        , -0.25      , -0.11111111, -0.0625    ,
        -0.11111111, -0.0625    , -0.04      , -0.11111111, -0.0625    ,
        -0.04      ],
       [-0.0625    , -1.        , -0

In [14]:
L_u = L[3:,3:]
B_T = L[3:,:3]
M1 = np.matrix([[1], [0],[0]])
R_hs = -B_T *M1
x_l1 = np.linalg.solve(L_u, R_hs)
x_l1

matrix([[ 0.3233404 ],
        [ 0.25386773],
        [ 0.27218854],
        [ 0.46748425],
        [ 0.33895493],
        [ 0.31510865],
        [ 0.29049825],
        [ 0.44537198],
        [ 0.34424346],
        [ 0.27103464],
        [ 0.54049922],
        [ 0.40470093],
        [ 0.30188053]])

In [26]:
L_u = L_3[3:,3:]
B_T = L_3[3:,:3]
M2 = np.matrix([[0], [1],[0]])
R_hs = -B_T *M2
x_l2 = np.linalg.solve(L_u, R_hs)
x_l2

matrix([[ 0.22396503],
        [ 0.2975915 ],
        [ 0.23622182],
        [ 0.43035913],
        [ 0.24522157],
        [ 0.17185223],
        [ 0.48470044],
        [ 0.25156424],
        [ 0.47570069],
        [ 0.25156424],
        [ 0.23622182],
        [ 0.4634439 ],
        [ 0.25687837]])

In [ ]:
M2 = np.matrix([[0], [1],[0]])
R_hs = -B_T *M2
x_l2 = np.linalg.solve(L_u, R_hs)
x_l2

In [28]:
M3 = np.matrix([[0], [0],[1]])
R_hs = -B_T *M3
x_l3 = np.linalg.solve(L_u, R_hs)
x_l3

matrix([[ 0.32037161],
        [ 0.52162694],
        [ 0.20967575],
        [ 0.16538354],
        [ 0.27459435],
        [ 0.26923667],
        [ 0.23215194],
        [ 0.26216845],
        [ 0.35227227],
        [ 0.38934532],
        [ 0.37667966],
        [ 0.37168538],
        [ 0.47064664]])

In [3]:
#import the necessary packages
from skimage.segmentation import slic
from skimage.segmentation import mark_boundaries
from skimage.util import img_as_float
from skimage import io
import matplotlib.pyplot as plt
import argparse
 
# construct the argument parser and parse the arguments
#ap = argparse.ArgumentParser()
#ap.add_argument("-i", "--image", required = True, help = "imagetest.png")
#args = vars(ap.parse_args())
 
# load the image and convert it to a floating point data type
image = img_as_float(io.imread("imagetest.png"))
 
# loop over the number of segments
for numSegments in (100, 200, 300):
	# apply SLIC and extract (approximately) the supplied number
	# of segments
	segments = slic(image, n_segments = numSegments, sigma = 5)
 
	# show the output of SLIC
	fig = plt.figure("Superpixels -- %d segments" % (numSegments))
	ax = fig.add_subplot(1, 1, 1)
	ax.imshow(mark_boundaries(image, segments))
	plt.axis("off")
 
# show the plots
plt.show()

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2548,4)