In [1]:
import networkx as nx
import pylab as plt
from scipy.linalg import eigvals

G = nx.Graph()
G.add_edges_from([(1,2),(2,3),(2,4),(3,5),(4,5)])
L = nx.normalized_laplacian_matrix(G)
Eig_norm = eigvals(L.todense())
print(Eig_norm)

[0.        +0.j 0.59175171+0.j 2.        +0.j 1.40824829+0.j
 1.        +0.j]


In [2]:
import networkx as nx
import pylab as plt
from scipy.linalg import eigvals

G = nx.Graph()
G.add_edges_from([(1,2),(1,3),(2,3),(3,4),(2,4)])
L = nx.laplacian_matrix(G)
Eig_norm = eigvals(L.todense())
print(Eig_norm)

[-2.22044605e-16+0.j  2.00000000e+00+0.j  4.00000000e+00+0.j
  4.00000000e+00+0.j]


In [4]:
import numpy as np

L = np.matrix([[1,0,0,-1],[0,0,0,0,],[0,0,0,0],[-1,0,0,1]])
Eig_norm = eigvals(L)
print(Eig_norm)

[2.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [2]:
L = nx.laplacian_matrix(G)
Eig = eigvals(L.todense())
print(Eig)

[ 4.48119430e+00+0.j  2.68889218e+00+0.j -2.80748585e-16+0.j
  8.29913513e-01+0.j  2.00000000e+00+0.j]


In [4]:
from numpy import linalg as LA

L = nx.laplacian_matrix(G)
w, v = LA.eig(L.todense())

In [5]:
w

array([ 4.48119430e+00,  2.68889218e+00, -2.80748585e-16,  8.29913513e-01,
        2.00000000e+00])

In [6]:
v

matrix([[ 2.01774144e-01,  3.17515788e-01, -4.47213595e-01,
          8.11462211e-01, -2.22044605e-16],
        [-7.02415001e-01, -5.36249932e-01, -4.47213595e-01,
          1.38018756e-01,  2.22044605e-16],
        [ 4.19319477e-01, -2.42173667e-01, -4.47213595e-01,
         -2.55974786e-01, -7.07106781e-01],
        [ 4.19319477e-01, -2.42173667e-01, -4.47213595e-01,
         -2.55974786e-01,  7.07106781e-01],
        [-3.37998097e-01,  7.03081478e-01, -4.47213595e-01,
         -4.37531395e-01,  6.50353591e-17]])

In [7]:
L = nx.normalized_laplacian_matrix(G)
w, v = LA.eig(L.todense())

In [8]:
w

array([0.        , 0.59175171, 2.        , 1.40824829, 1.        ])

In [9]:
v

matrix([[ 3.16227766e-01, -6.32455532e-01,  3.16227766e-01,
         -6.32455532e-01,  9.61481343e-17],
        [ 5.47722558e-01, -4.47213595e-01, -5.47722558e-01,
          4.47213595e-01,  8.78224055e-32],
        [ 4.47213595e-01,  2.23606798e-01,  4.47213595e-01,
          2.23606798e-01,  7.07106781e-01],
        [ 4.47213595e-01,  2.23606798e-01,  4.47213595e-01,
          2.23606798e-01, -7.07106781e-01],
        [ 4.47213595e-01,  5.47722558e-01, -4.47213595e-01,
         -5.47722558e-01, -1.57009246e-16]])

In [10]:
G.degree()

{1: 1, 2: 3, 3: 2, 4: 2, 5: 2}