In [2]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[1,-1,0,0], [-1,3,-1,-1],[0,-1,1,0],[0,-1,0,1]])
l = lp.eigvals(m)
le = np.sum(np.square(l))
le

18.000000000000007

In [3]:
m = np.matrix([[2,-1,-1], [-1,1,0],[-1,0,1]])
l = lp.eigvals(m)
l1 = np.sum(np.square(l))
l1

10.0

In [4]:
m = np.matrix([[1,-1,0], [-1,2,-1],[0,-1,1]])
l = lp.eigvals(m)
l3 = np.sum(np.square(l))
l3

9.9999999999999947

In [5]:
m = np.matrix([[5/4,-1,-1/8,-1/8], [-1,3,-1,-1],[-1/8,-1,5/4,-1/8],[-1/8,-1,-1/8,5/4]])
l = lp.eigvals(m)
le = np.sum(np.square(l))
le

19.781250000000004

In [6]:
m = np.matrix([[2,-1,-1], [-1,9/8,-1/8],[-1,-1/8,9/8]])
l = lp.eigvals(m)
l1 = np.sum(np.square(l))
l1

10.562499999999998

In [7]:
m = np.matrix([[9/8,-1,-1/8], [-1,2,-1],[-1/8,-1,9/8]])
l = lp.eigvals(m)
l3 = np.sum(np.square(l))
l3

10.562499999999993

In [8]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[0,2,-1,-1], [0,0,0,0],[-1,0,2,-1],[-1,0,-1,2]])
l = lp.eigvals(m)
le = np.sum(np.square(l))
le

13.999999999999998

In [3]:
import numpy as np
import numpy.linalg as lp
from numpy import linalg as LA

m1 = np.matrix([[1,-1,0,0,0], [-1,3,-1,0,-1],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,-1,0,-1,2]])
m2 = np.matrix([[2,0,-1,0,-1],[0,1,0,-1,0],[-1,0,2,0,-1],[0,-1,0,1,0],[-1,0,-1,0,2]])
w1, v1 = LA.eigh(m1)
w2, v2 = LA.eigh(m2)
print(v1)

[[ -4.47213595e-01   8.11462211e-01   0.00000000e+00  -3.17515788e-01
    2.01774144e-01]
 [ -4.47213595e-01   1.38018756e-01   0.00000000e+00   5.36249932e-01
   -7.02415001e-01]
 [ -4.47213595e-01  -2.55974786e-01  -7.07106781e-01   2.42173667e-01
    4.19319477e-01]
 [ -4.47213595e-01  -4.37531395e-01   2.87079964e-16  -7.03081478e-01
   -3.37998097e-01]
 [ -4.47213595e-01  -2.55974786e-01   7.07106781e-01   2.42173667e-01
    4.19319477e-01]]


In [4]:
print(v2)

[[ -5.77350269e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
   -8.16496581e-01]
 [  0.00000000e+00   7.07106781e-01   7.07106781e-01   3.33066907e-16
    0.00000000e+00]
 [ -5.77350269e-01   2.22044605e-16   1.11022302e-16  -7.07106781e-01
    4.08248290e-01]
 [  0.00000000e+00   7.07106781e-01  -7.07106781e-01   1.11022302e-16
    0.00000000e+00]
 [ -5.77350269e-01   1.11022302e-16  -1.11022302e-16   7.07106781e-01
    4.08248290e-01]]


In [13]:
import numpy as np
import networkx as nx
import numpy.linalg as lp
from numpy import linalg as LA
import itertools

def kplaplacian_mlf(G,lam):
    nodes = G.nodes()
    nodelist = list(itertools.combinations(nodes,2))
    nsize    = len(nodes)
    L = np.zeros(shape=(nsize,nsize))
    for n in nodelist:
        k = nx.shortest_path_length(G, source=n[0], target=n[1])
        if k==1:
            L[n[0]-1,n[1]-1]= L[n[1]-1,n[0]-1]= -1
        else:
            L[n[0]-1,n[1]-1]= L[n[1]-1,n[0]-1]= -pow(k,-1*lam)
    row,col = np.diag_indices_from(L)
    L[row,col] = -L.sum(axis=1)
    return L
G = nx.Graph()
G.add_edges_from([(1,2),(2,3),(3,4),(4,5),(5,2)])
L = kplaplacian_mlf(G,lam=2)
w, v = LA.eigh(L)
print(v)

[[  4.47213595e-01   8.03375866e-01   0.00000000e+00  -3.48311989e-01
    1.82389627e-01]
 [  4.47213595e-01   1.37792908e-01  -1.24319103e-17   5.16516949e-01
   -7.17093687e-01]
 [  4.47213595e-01  -2.31732973e-01  -7.07106781e-01   2.60806532e-01
    4.22231906e-01]
 [  4.47213595e-01  -4.77702827e-01  -1.39446326e-16  -6.89818023e-01
   -3.09759752e-01]
 [  4.47213595e-01  -2.31732973e-01   7.07106781e-01   2.60806532e-01
    4.22231906e-01]]


In [15]:
G1 = nx.complete_graph(5)
L1 = nx.laplacian_matrix(G1)
w1, v1 = LA.eigh(L1.todense())
print(v1)

[[ 0.4472136   0.30943831 -0.42598052  0.72304117  0.        ]
 [ 0.4472136  -0.87222952 -0.108859    0.03254229  0.16219245]
 [ 0.4472136   0.1210157   0.86649119  0.18209402 -0.03728243]
 [ 0.4472136   0.09591574 -0.18688422 -0.42776132 -0.75689808]
 [ 0.4472136   0.34585976 -0.14476745 -0.50991616  0.63198807]]
