In [9]:
import numpy as np
import networkx as nx
from scipy.sparse import identity

G = nx.Graph([(1,2),(2,3),(2,4),(2,5),(3,4)])
Ln =nx.normalized_laplacian_matrix(G)
Ln.todense()

matrix([[ 1.        , -0.5       ,  0.        ,  0.        ,  0.        ],
        [-0.5       ,  1.        , -0.35355339, -0.35355339, -0.5       ],
        [ 0.        , -0.35355339,  1.        , -0.5       ,  0.        ],
        [ 0.        , -0.35355339, -0.5       ,  1.        ,  0.        ],
        [ 0.        , -0.5       ,  0.        ,  0.        ,  1.        ]])

In [11]:
I = identity(5)
Pn = I-Ln
Pn.todense()

matrix([[0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [5.00000000e-01, 0.00000000e+00, 3.53553391e-01, 3.53553391e-01,
         5.00000000e-01],
        [0.00000000e+00, 3.53553391e-01, 2.22044605e-16, 5.00000000e-01,
         0.00000000e+00],
        [0.00000000e+00, 3.53553391e-01, 5.00000000e-01, 2.22044605e-16,
         0.00000000e+00],
        [0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00]])

In [13]:
from numpy import linalg as LA
w, v = LA.eigh(Ln.todense())

In [14]:
w

array([2.58473798e-16, 6.90983006e-01, 1.00000000e+00, 1.50000000e+00,
       1.80901699e+00])

In [15]:
v

matrix([[-3.16227766e-01,  4.47213595e-01, -7.07106781e-01,
          0.00000000e+00, -4.47213595e-01],
        [-6.32455532e-01,  2.76393202e-01, -1.58633442e-16,
          0.00000000e+00,  7.23606798e-01],
        [-4.47213595e-01, -5.11667274e-01,  2.22044605e-16,
         -7.07106781e-01, -1.95439508e-01],
        [-4.47213595e-01, -5.11667274e-01,  2.22044605e-16,
          7.07106781e-01, -1.95439508e-01],
        [-3.16227766e-01,  4.47213595e-01,  7.07106781e-01,
         -5.55111512e-17, -4.47213595e-01]])

In [22]:
v[:,4]

matrix([[-0.4472136 ],
        [ 0.7236068 ],
        [-0.19543951],
        [-0.19543951],
        [-0.4472136 ]])