In [1]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[1,-1,0,0,0], [-1,3,-1,0,-1],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,-1,0,-1,2]])
a,v = lp.eigh(m)
print(a)
print(v)

[ -3.28437692e-16   8.29913513e-01   2.00000000e+00   2.68889218e+00
   4.48119430e+00]
[[ -4.47213595e-01   8.11462211e-01   0.00000000e+00  -3.17515788e-01
    2.01774144e-01]
 [ -4.47213595e-01   1.38018756e-01   0.00000000e+00   5.36249932e-01
   -7.02415001e-01]
 [ -4.47213595e-01  -2.55974786e-01  -7.07106781e-01   2.42173667e-01
    4.19319477e-01]
 [ -4.47213595e-01  -4.37531395e-01   2.87079964e-16  -7.03081478e-01
   -3.37998097e-01]
 [ -4.47213595e-01  -2.55974786e-01   7.07106781e-01   2.42173667e-01
    4.19319477e-01]]


In [12]:
import numpy as np
import numpy.linalg as lp
import scipy.linalg as ln
m = np.matrix([[0,1,1,1,1], [1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0]])
e,v = lp.eig(m)
print(ln.expm(m))

[[ 3.76219569  1.8134302   1.8134302   1.8134302   1.8134302 ]
 [ 1.8134302   1.69054892  0.69054892  0.69054892  0.69054892]
 [ 1.8134302   0.69054892  1.69054892  0.69054892  0.69054892]
 [ 1.8134302   0.69054892  0.69054892  1.69054892  0.69054892]
 [ 1.8134302   0.69054892  0.69054892  0.69054892  1.69054892]]


In [14]:
d = np.diag(np.exp(e))
np.dot(np.dot(v,d), v.transpose())

matrix([[ 3.76219569,  1.8134302 ,  1.8134302 ,  1.8134302 ,  1.8134302 ],
        [ 1.8134302 ,  1.69054892,  0.69054892,  0.69054892,  0.69054892],
        [ 1.8134302 ,  0.69054892,  1.69054892,  0.69054892,  0.69054892],
        [ 1.8134302 ,  0.69054892,  0.69054892,  1.69054892,  0.69054892],
        [ 1.8134302 ,  0.69054892,  0.69054892,  0.69054892,  1.69054892]])

In [17]:
0.5*(m*m)

matrix([[ 2. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0.5,  0.5,  0.5,  0.5],
        [ 0. ,  0.5,  0.5,  0.5,  0.5],
        [ 0. ,  0.5,  0.5,  0.5,  0.5],
        [ 0. ,  0.5,  0.5,  0.5,  0.5]])

In [ ]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[1,-1,0,0,0], [-1,3,-1,0,-1],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,-1,0,-1,2]])
a = lp.eigvals(m)
print(a)

In [4]:
ee = np.exp(-0.1*m)
ee

matrix([[ 0.90483742,  1.10517092,  1.        ,  1.        ,  1.        ],
        [ 1.10517092,  0.74081822,  1.10517092,  1.        ,  1.10517092],
        [ 1.        ,  1.10517092,  0.81873075,  1.10517092,  1.        ],
        [ 1.        ,  1.        ,  1.10517092,  0.81873075,  1.10517092],
        [ 1.        ,  1.10517092,  1.        ,  1.10517092,  0.81873075]])

In [3]:
m = np.matrix([[2,0,-1,0,-1], [0,1,0,-1,0],[-1,0,2,0,-1],[0,-1,0,1,0],[-1,0,-1,0,2]])
a,v = lp.eigh(m)
print(a)
print(v)

[ -1.11022302e-16   4.85722573e-16   2.00000000e+00   3.00000000e+00
   3.00000000e+00]
[[ -5.77350269e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
   -8.16496581e-01]
 [  0.00000000e+00   7.07106781e-01   7.07106781e-01   4.44089210e-16
    0.00000000e+00]
 [ -5.77350269e-01   5.55111512e-17   2.22044605e-16  -7.07106781e-01
    4.08248290e-01]
 [  0.00000000e+00   7.07106781e-01  -7.07106781e-01   0.00000000e+00
    0.00000000e+00]
 [ -5.77350269e-01   2.22044605e-16   0.00000000e+00   7.07106781e-01
    4.08248290e-01]]


In [2]:
m = np.matrix([[2,0,-1,0,-1], [0,1,0,-1,0],[-1,0,2,0,-1],[0,-1,0,1,0],[-1,0,-1,0,2]])
a = lp.eigvals(m)
print(a)

[  3.00000000e+00  -2.22044605e-16   0.00000000e+00   2.00000000e+00
   3.00000000e+00]


In [4]:
m = np.matrix([[1,0,0,-1,0], [0,0,0,0,0],[0,0,0,0,0],[-1,0,0,1,0],[0,0,0,0,0]])
a,v = lp.eigh(m)
print(a)
print(v)

[ 0.  0.  0.  0.  2.]
[[-0.70710678  0.          0.          0.         -0.70710678]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [-0.70710678  0.          0.          0.          0.70710678]
 [-0.          0.          0.          1.          0.        ]]


In [21]:
m = np.matrix([[2,-1,-1,0,0], [-1,2,-1,0,0],[-1,-1,4,-1,-1],[0,0,-1,1,0],[0,0,-1,0,1]])
a,v = lp.eigh(m)
print(a)
print(v)

[ -7.12672940e-16   1.00000000e+00   1.00000000e+00   3.00000000e+00
   5.00000000e+00]
[[  4.47213595e-01   4.93301133e-01  -8.15720074e-02   7.07106781e-01
   -2.23606798e-01]
 [  4.47213595e-01   4.93301133e-01  -8.15720074e-02  -7.07106781e-01
   -2.23606798e-01]
 [  4.47213595e-01   5.55111512e-17   6.24500451e-17  -2.22044605e-16
    8.94427191e-01]
 [  4.47213595e-01  -6.08661372e-01  -6.16061145e-01  -3.88578059e-16
   -2.23606798e-01]
 [  4.47213595e-01  -3.77940894e-01   7.79205160e-01  -3.05311332e-16
   -2.23606798e-01]]


In [22]:
m = np.matrix([[2,0,0,-1,-1], [0,2,0,-1,-1],[0,0,0,0,0],[-1,-1,0,3,-1],[-1,-1,0,-1,3]])
a,v = lp.eigh(m)
print(a)
print(v)

[ -3.13364331e-16   7.78331501e-17   2.00000000e+00   4.00000000e+00
   4.00000000e+00]
[[  4.46705764e-01  -2.24619590e-01  -7.07106781e-01  -5.00000000e-01
    2.68606496e-18]
 [  4.46705764e-01  -2.24619590e-01   7.07106781e-01  -5.00000000e-01
   -1.14820972e-16]
 [ -4.49239179e-01  -8.93411529e-01   1.11022302e-16   0.00000000e+00
    2.80241821e-16]
 [  4.46705764e-01  -2.24619590e-01  -2.22044605e-16   5.00000000e-01
   -7.07106781e-01]
 [  4.46705764e-01  -2.24619590e-01  -2.22044605e-16   5.00000000e-01
    7.07106781e-01]]


In [20]:
#print(v[:,0])
np.dot(m,v[:,0])

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [2]:
m = np.matrix([[6,-4,-2,0,0,0], [-4,9,-1,-2,-2,0],[-2,-1,3,0,0,0],
               [0,-2,0,2,0,0],[0,-2,0,0,3,-1],[0,0,0,0,-1,1]])
l = lp.eigvals(m)
print(l)

[  1.23471746e+01   5.74675876e+00  -7.52158225e-16   7.50252174e-01
   2.00000000e+00   3.15581447e+00]


In [4]:
m = np.matrix([[12,0,0,-6,-6,0], [0,3,0,0,0,-3],[0,0,6,-3,-3,0],
               [-6,0,-3,13,-4,0],[-6,0,-3,-4,13,0],[0,-3,0,0,0,3]])
l = lp.eigvals(m)
print(l)

[  1.96846584e+01   7.31534156e+00   2.31171560e-15  -8.88178420e-16
   6.00000000e+00   1.70000000e+01]


In [3]:
m = np.matrix([[7,0,0,0,0,-7], [0,0,0,0,0,0],[0,0,4,0,0,-4],
               [0,0,0,5,0,-5],[0,0,0,0,0,0],[-7,0,-4,-5,0,16]])
l = lp.eigvals(m)
print(l)

[  2.17250894e+01   7.59581223e-16   5.92282023e+00   4.35209036e+00
   0.00000000e+00   0.00000000e+00]


In [8]:
m = np.matrix([[15,-10,-3,-2], [-10,17,0,-7],[-3,0,9,-6],[-2,0,-6,8]])
l = lp.eigvals(m)
print(l)

[  2.61072533e+01  -5.61356517e-15   8.86060472e+00   1.40321420e+01]


In [9]:
m = np.matrix([[0,0,0,0], [0,13,-13,0],[0,-13,13,0],[0,0,0,0]])
l = lp.eigvals(m)
print(l)

[  2.60000000e+01  -3.55271368e-15   0.00000000e+00   0.00000000e+00]


In [4]:
m = np.matrix([[6,-4,-2,0,0,0], [-4,11,-1,-4,-2,0],[-2,-1,3,0,0,0],
               [0,-4,0,4,0,0],[0,-2,0,0,3,-1],[0,0,0,0,-1,1]])
l = lp.eigvals(m)
print(l)

[  1.46847904e+01   6.32416040e+00   7.64093827e-16   7.60032618e-01
   2.68452579e+00   3.54649074e+00]


In [3]:
m = np.matrix([[14,0,0,-8,-6,0], [0,3,0,0,0,-3],[0,0,8,-5,-3,0],
               [-8,0,-5,19,-6,0],[-6,0,-3,-6,15,0],[0,-3,0,0,0,3]])
l = lp.eigvals(m)
print(l)

[  0.00000000e+00   9.48969969e+00   2.59329835e+01   2.05773169e+01
   4.44089210e-16   6.00000000e+00]


In [4]:
m = np.matrix([[2,0,0,-1,-1,0], [0,1,0,0,0,-1],[0,0,2,-1,-1,0],
               [-1,0,-1,3,-1,0],[-1,0,-1,-1,3,0],[0,-1,0,0,0,1]])
l = lp.eigvals(m)
print(l)

[ -2.22044605e-16   2.00000000e+00   4.00000000e+00   0.00000000e+00
   2.00000000e+00   4.00000000e+00]


In [5]:
m = np.matrix([[7,0,0,0,0,-7], [0,0,0,0,0,0],[0,0,4,0,0,-4],
               [0,0,0,7,0,-7],[0,0,0,0,0,0],[-7,0,-4,-7,0,18]])
l = lp.eigvals(m)
print(l)

[  2.44121138e+01   3.64195057e-16   7.00000000e+00   4.58788620e+00
   0.00000000e+00   0.00000000e+00]


In [6]:
m = np.matrix([[1,0,0,0,0,-1], [0,0,0,0,0,0],[0,0,1,0,0,-1],
               [0,0,0,1,0,-1],[0,0,0,0,0,0],[-1,0,-1,-1,0,3]])
l = lp.eigvals(m)
print(l)

[  4.00000000e+00  -2.49366500e-16   1.00000000e+00   1.00000000e+00
   0.00000000e+00   0.00000000e+00]


In [7]:
m = np.matrix([[7/4,0,0,0,0,-7/4], [0,0,0,0,0,0],[0,0,5/2,0,0,-5/2],
               [0,0,0,7/4,0,-7/4],[0,0,0,0,0,0],[-7/4,0,-5/4,-7/4,0,19/4]])
l = lp.eigvals(m)
print(l)

[  6.72204860e+00  -4.37800837e-16   2.27795140e+00   1.75000000e+00
   0.00000000e+00   0.00000000e+00]


In [2]:
m = np.matrix([[2,-1,0,-1], [-1,3,-1,-1],[0,-1,2,-1],[-1,-1,-1,3]])
l = lp.eigvals(m)
print(l)

[ -2.22044605e-16   2.00000000e+00   4.00000000e+00   4.00000000e+00]


In [3]:
m = np.matrix([[1,0,-1,0], [0,0,0,0],[-1,0,1,0],[0,0,0,0]])
l = lp.eigvals(m)
print(l)

[ 2.  0.  0.  0.]


In [2]:
m = np.matrix([[1,0,-1,0,0], [0,1,0,-1,0],[-1,0,2,0,-1],[0,-1,0,1,0],[0,0,-1,0,1]])
l = lp.eigvals(m)
print(l)

[  3.00000000e+00   1.00000000e+00  -3.36770206e-17   2.00000000e+00
   0.00000000e+00]


In [4]:
#another graph
m = np.matrix([[1,0,-1,0,0,0], [0,2,-2,0,0,0],[-1,-2,11,-4,-4,0],[0,0,-4,7,-2,-1],
               [0,0,-4,-2,11,-5],[0,0,0,-1,-5,6]])
l = lp.eigvals(m)
print(l)

[  1.66421291e+01   1.20067982e+01   6.10699334e+00   7.04696976e-16
   1.22270035e+00   2.02137904e+00]


In [5]:
m = np.matrix([[13,-3,0,-5,-5,0], [-3,15,0,-6,-6,0],[0,0,5,0,0,-5],[-5,-6,0,11,0,0],
               [-5,-6,0,0,11,0],[0,0,-5,0,0,5]])
l = lp.eigvals(m)
print(l)

[ -3.55271368e-15   1.66277187e+01   2.23722813e+01   1.77635684e-15
   1.00000000e+01   1.10000000e+01]


In [6]:
m = np.matrix([[6,0,0,0,0,-6], [0,7,0,0,0,-7],[0,0,0,0,0,0],[0,0,0,0,0,0],
               [0,0,0,0,0,0],[-6,-7,0,0,0,13]])
l = lp.eigvals(m)
print(l)

[  1.95574385e+01   6.44256148e+00   1.23056788e-17   0.00000000e+00
   0.00000000e+00   0.00000000e+00]


In [4]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[1,-1,0,0], [-1,2,-1,0],[0,-1,2,-1],[0,0,-1,1]])
m*m*m

matrix([[  5,  -9,   5,  -1],
        [ -9,  19, -15,   5],
        [  5, -15,  19,  -9],
        [ -1,   5,  -9,   5]])

In [3]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[2,-1,-1,0,0,0], [-1,2,-1,0,0,0],[-1,-1,4,-1,-1,0],
               [0,0,-1,1,0,0],[0,0,-1,0,2,-1],[0,0,0,0,-1,1]])
l = lp.eigvals(m)
print(l)

[  5.08613020e+00   3.00000000e+00   2.42800673e+00  -4.36299408e-16
   1.00000000e+00   4.85863071e-01]


In [7]:
ll = np.sum(np.square(l))
ll

42.0

In [8]:
m = np.matrix([[2,-1,-1,0,0], [-1,2,-1,0,0],[-1,-1,3,-1,0],
               [0,0,-1,2,-1],[0,0,0,-1,1]])
l = lp.eigvals(m)
ll = np.sum(np.square(l))
ll

32.000000000000007

In [9]:
m = np.matrix([[1,-1,0,0,0], [-1,1,0,0,0],[0,0,0,0,0],
               [0,0,0,1,-1],[0,0,0,-1,1]])
l = lp.eigvals(m)
ll = np.sum(np.square(l))
ll

8.0

In [10]:
m = np.matrix([[2.287,-1,-1,-1/8,-1/8,-1/27], [-1,2.287,-1,-1/8,-1/8,-1/27],
               [-1,-1,4.125,-1,-1,-1/8],
               [-1/8,-1/8,-1,1.5,-1/8,-1/27],[-1/8,-1/8,-1,-1/8,2.375,-1],
              [-1/27,-1/27,-1/8,-1/27,-1,1.2361]])
l = lp.eigvals(m)
ll = np.sum(np.square(l))
ll

49.090661662674918

In [5]:
import numpy as np
import numpy.linalg as lp


m = np.matrix([[0,-23/57,-61/570,-69/570], [0,1,-31/38,0],[0,0,1,0],[0,0,-32/38,1]])
#v = lp.inv(m)


In [8]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[0,10,2,3], [0,0,7,0],[0,3,0,0],[0,0,6,0]])
#v = lp.inv(m)
