In [11]:
import numpy as np
import networkx as nx
from numpy import linalg as LA

G = nx.Graph()
edgelst = [(1,2,2.0),(1,3,1.0),(2,3,3.0),(2,4,2.0)]
G.add_weighted_edges_from(edgelst)
path = nx.all_pairs_dijkstra_path(G, weight='weight')
D = nx.floyd_warshall_numpy(G, weight='weight')
D

matrix([[ 0.,  2.,  1.,  4.],
        [ 2.,  0.,  3.,  2.],
        [ 1.,  3.,  0.,  5.],
        [ 4.,  2.,  5.,  0.]])

In [11]:

#3by3 lattice

import numpy as np
import networkx as nx
from numpy import linalg as LA

G = nx.Graph()
edgelst = [(1,2,1.0),(1,4,1.0),(2,3,1.0),(2,8,2.0),(3,5,3.0),(4,8,1.5),
          (4,6,2.0),(6,7,3.0),(8,5,1.5),(8,7,2.5),(5,9,4.0),(7,9,1.0)]
G.add_weighted_edges_from(edgelst)
D = nx.floyd_warshall_numpy(G, weight='weight')
D

matrix([[ 0. ,  1. ,  2. ,  1. ,  4. ,  3. ,  5. ,  2.5,  6. ],
        [ 1. ,  0. ,  1. ,  2. ,  3.5,  4. ,  4.5,  2. ,  5.5],
        [ 2. ,  1. ,  0. ,  3. ,  3. ,  5. ,  5.5,  3. ,  6.5],
        [ 1. ,  2. ,  3. ,  0. ,  3. ,  2. ,  4. ,  1.5,  5. ],
        [ 4. ,  3.5,  3. ,  3. ,  0. ,  5. ,  4. ,  1.5,  4. ],
        [ 3. ,  4. ,  5. ,  2. ,  5. ,  0. ,  3. ,  3.5,  4. ],
        [ 5. ,  4.5,  5.5,  4. ,  4. ,  3. ,  0. ,  2.5,  1. ],
        [ 2.5,  2. ,  3. ,  1.5,  1.5,  3.5,  2.5,  0. ,  3.5],
        [ 6. ,  5.5,  6.5,  5. ,  4. ,  4. ,  1. ,  3.5,  0. ]])

In [15]:
D1 = nx.floyd_warshall_numpy(G, weight='None')
D1
v = np.power(D1,3)
vv = np.divide(D,v)
print(vv)

[[        nan  1.          0.25        1.          0.14814815  0.375
   0.18518519  0.3125      0.09375   ]
 [ 1.                 nan  1.          0.25        0.4375      0.14814815
   0.5625      2.          0.2037037 ]
 [ 0.25        1.                 nan  0.11111111  3.          0.078125
   0.2037037   0.375       0.8125    ]
 [ 1.          0.25        0.11111111         nan  0.375       2.          0.5
   1.5         0.18518519]
 [ 0.14814815  0.4375      3.          0.375              nan  0.18518519
   0.5         1.5         4.        ]
 [ 0.375       0.14814815  0.078125    2.          0.18518519         nan
   3.          0.4375      0.5       ]
 [ 0.18518519  0.5625      0.2037037   0.5         0.5         3.
          nan  2.5         1.        ]
 [ 0.3125      2.          0.375       1.5         1.5         0.4375      2.5
          nan  0.4375    ]
 [ 0.09375     0.2037037   0.8125      0.18518519  4.          0.5         1.
   0.4375             nan]]


/usr/lib/python3/dist-packages/ipykernel/__main__.py:4: RuntimeWarning: invalid value encountered in true_divide


In [21]:
#4by3 lattice

import numpy as np
import networkx as nx
from numpy import linalg as LA

G = nx.Graph()
edgelst = [(1,2,1.0),(1,4,1.0),(2,3,1.0),(2,10,2.0),(3,5,3.0),(3,12,2.0),
           (4,10,1.5),
          (4,6,2.0),(6,7,3.0),(10,5,1.5),(10,7,2.5),(5,11,4.0),(5,8,3.0),
           (8,12,1.5),
           (8,9,1.0),(11,9,1.0),(7,11,1.0)]
G.add_weighted_edges_from(edgelst)
print(nx.degree(G))
D = nx.floyd_warshall_numpy(G, weight='weight')
D

{1: 2, 2: 3, 3: 3, 4: 3, 5: 4, 6: 2, 7: 3, 8: 3, 9: 2, 10: 4, 11: 3, 12: 2}


matrix([[ 0. ,  1. ,  2. ,  1. ,  4. ,  3. ,  5. ,  5.5,  6.5,  2.5,  6. ,
          4. ],
        [ 1. ,  0. ,  1. ,  2. ,  3.5,  4. ,  4.5,  4.5,  5.5,  2. ,  5.5,
          3. ],
        [ 2. ,  1. ,  0. ,  3. ,  3. ,  5. ,  5.5,  3.5,  4.5,  3. ,  5.5,
          2. ],
        [ 1. ,  2. ,  3. ,  0. ,  3. ,  2. ,  4. ,  6. ,  6. ,  1.5,  5. ,
          5. ],
        [ 4. ,  3.5,  3. ,  3. ,  0. ,  5. ,  4. ,  3. ,  4. ,  1.5,  4. ,
          4.5],
        [ 3. ,  4. ,  5. ,  2. ,  5. ,  0. ,  3. ,  6. ,  5. ,  3.5,  4. ,
          7. ],
        [ 5. ,  4.5,  5.5,  4. ,  4. ,  3. ,  0. ,  3. ,  2. ,  2.5,  1. ,
          4.5],
        [ 5.5,  4.5,  3.5,  6. ,  3. ,  6. ,  3. ,  0. ,  1. ,  4.5,  2. ,
          1.5],
        [ 6.5,  5.5,  4.5,  6. ,  4. ,  5. ,  2. ,  1. ,  0. ,  4.5,  1. ,
          2.5],
        [ 2.5,  2. ,  3. ,  1.5,  1.5,  3.5,  2.5,  4.5,  4.5,  0. ,  3.5,
          5. ],
        [ 6. ,  5.5,  5.5,  5. ,  4. ,  4. ,  1. ,  2. ,  1. ,  3.5,  0. ,
          3.5],

In [23]:
D1 = nx.floyd_warshall_numpy(G, weight='None')
D1
v = np.power(D1,3)
print(v)

[[   0.    1.    8.    1.   27.    8.   27.   64.  125.    8.   64.   27.]
 [   1.    0.    1.    8.    8.   27.    8.   27.   64.    1.   27.    8.]
 [   8.    1.    0.   27.    1.   64.   27.    8.   27.    8.    8.    1.]
 [   1.    8.   27.    0.    8.    1.    8.   27.   64.    1.   27.   64.]
 [  27.    8.    1.    8.    0.   27.    8.    1.    8.    1.    1.    8.]
 [   8.   27.   64.    1.   27.    0.    1.   64.   27.    8.    8.  125.]
 [  27.    8.   27.    8.    8.    1.    0.   27.    8.    1.    1.   64.]
 [  64.   27.    8.   27.    1.   64.   27.    0.    1.    8.    8.    1.]
 [ 125.   64.   27.   64.    8.   27.    8.    1.    0.   27.    1.    8.]
 [   8.    1.    8.    1.    1.    8.    1.    8.   27.    0.    8.   27.]
 [  64.   27.    8.   27.    1.    8.    1.    8.    1.    8.    0.   27.]
 [  27.    8.    1.   64.    8.  125.   64.    1.    8.   27.   27.    0.]]


In [12]:
import numpy as np
import numpy.linalg as lp

m = np.matrix([[2,-1,-1,0], [-1,3,-1,-1],[-1,-1,2,0],[0,-1,0,1]])
a,v = lp.eigh(m)
print(a)
print(v)

[ -9.43689571e-16   1.00000000e+00   3.00000000e+00   4.00000000e+00]
[[  5.00000000e-01  -4.08248290e-01   7.07106781e-01   2.88675135e-01]
 [  5.00000000e-01   2.22044605e-16  -6.66133815e-16  -8.66025404e-01]
 [  5.00000000e-01  -4.08248290e-01  -7.07106781e-01   2.88675135e-01]
 [  5.00000000e-01   8.16496581e-01   2.22044605e-16   2.88675135e-01]]


In [14]:
m = np.matrix([[3,-2,-1,0], [-2,7,-3,-2],[-1,-3,4,0],[0,-2,0,2]])
a,v = lp.eigh(m)
print(a)
print(v)

[ -1.22625389e-15   2.11176399e+00   4.38492837e+00   9.50330763e+00]
[[-0.5        -0.46215823  0.7056588  -0.19610054]
 [-0.5        -0.04618527 -0.14773641  0.85208032]
 [-0.5        -0.31813504 -0.68181409 -0.42885853]
 [-0.5         0.82647854  0.12389169 -0.22712125]]
